import type { Source } from "@cim/db/schema";
import type { RawFetchResult, SourceConnector, SourceHealth } from "./connector";

const HEADLINE_TEMPLATES: ((name: string) => string)[] = [
  (name) => `${name} announces quarterly results`,
  (name) => `Analysts discuss ${name}'s market position`,
  (name) => `${name} expands into a new region`,
  (name) => `Customers react to ${name}'s latest update`,
  (name) => `${name} featured in industry roundup`,
  (name) => `${name} responds to competitor announcement`,
];

const BUCKET_MS = 60_000;

/**
 * docs/architecture/INGESTION.md §MockNewsConnector — ships as a
 * first-class connector (not a test-only stub) so the full ingestion
 * pipeline runs without live network access, in dev and in E2E tests
 * alike. Content is explicitly synthetic and says so in its own body
 * text (brief §122/§154 — never presented as real coverage).
 *
 * One deterministic item per one-minute time bucket per source: calling
 * `fetch` again within the same minute returns the same
 * canonicalUrl/content, so the pipeline's dedupe naturally no-ops; a new
 * minute produces a "new" article, giving the worker's repeat crawl
 * cycle something real to observe without unbounded growth.
 *
 * The bucket number is folded into the body text (not just the URL) so
 * that `contentHash` — computed from title+body — is unique per bucket
 * too. The headline template itself only cycles through six fixed
 * strings, so without this the content-hash half of the pipeline's
 * canonicalUrl-OR-contentHash dedupe would collide with an article from
 * six buckets ago and mask every subsequent minute as "not new".
 */
export class MockNewsConnector implements SourceConnector {
  async fetch(source: Source): Promise<RawFetchResult[]> {
    const bucket = Math.floor(Date.now() / BUCKET_MS);
    const template = HEADLINE_TEMPLATES[bucket % HEADLINE_TEMPLATES.length];
    if (!template) throw new Error("unreachable: modulo of a non-empty array");
    const title = template(source.name);
    const externalId = `${source.id}-${bucket}`;

    return [
      {
        externalId,
        canonicalUrl: `https://${source.domain}/mock/${externalId}`,
        title,
        bodyText: `${title}. Synthetic demo content generated by MockNewsConnector for local development and testing — not real coverage. (bucket ${bucket})`,
        language: source.language ?? "en",
        publishedAt: new Date(bucket * BUCKET_MS),
        authorName: null,
      },
    ];
  }

  async healthCheck(_source: Source): Promise<SourceHealth> {
    return { status: "healthy" };
  }
}
