import type { Source } from "@cim/db/schema";
import type { RawFetchResult, SourceConnector, SourceHealth } from "./connector";

const POST_TEMPLATES: ((name: string, handle: string) => string)[] = [
  (name) => `Just had a great experience with ${name} today.`,
  (name, handle) => `@${handle} really came through for us this week.`,
  (name) => `#${name.replace(/\s+/g, "")} is trending after today's announcement.`,
  (name) => `Anyone else following what's happening with ${name}?`,
  (name, handle) => `Shoutout to @${handle} for the fast support.`,
  (name) => `${name} keeps showing up in every conversation lately.`,
];

const HANDLES = [
  "mockuser1",
  "mockuser2",
  "mockuser3",
  "mockcreator",
  "mockjournalist",
];
const BUCKET_MS = 60_000;

/**
 * docs/architecture/ADR-006-SOCIAL-LISTENING.md — the social counterpart
 * to MockNewsConnector: ships as a first-class connector (not a
 * test-only stub) so the full Social Listening UX (match-type
 * classification, author cards, "Why matched?") is demonstrable and
 * E2E-testable without live platform APIs (master prompt §130). Content
 * is explicitly synthetic and says so in its own body text — never
 * presented as real social activity (brief §122/§154).
 *
 * Same one-item-per-minute-bucket determinism as MockNewsConnector, for
 * the same reason: a repeat crawl within the same minute is a no-op for
 * dedupe, a new minute produces a "new" post.
 */
export class MockSocialConnector implements SourceConnector {
  async fetch(source: Source): Promise<RawFetchResult[]> {
    const bucket = Math.floor(Date.now() / BUCKET_MS);
    const template = POST_TEMPLATES[bucket % POST_TEMPLATES.length];
    if (!template) throw new Error("unreachable: modulo of a non-empty array");
    const handle = HANDLES[bucket % HANDLES.length];
    if (!handle) throw new Error("unreachable: modulo of a non-empty array");
    const authorExternalId = `mock-author-${handle}`;
    const text = template(source.name, handle);
    const externalId = `${source.id}-${bucket}`;

    return [
      {
        externalId,
        canonicalUrl: `https://${source.domain}/mock-post/${externalId}`,
        title: text,
        bodyText: `${text} (Synthetic demo content generated by MockSocialConnector for local development and testing — not a real post. bucket ${bucket})`,
        language: source.language ?? "en",
        publishedAt: new Date(bucket * BUCKET_MS),
        authorName: `@${handle}`,
        socialPlatform: "mock",
        socialAuthorExternalId: authorExternalId,
        socialAuthorHandle: `@${handle}`,
        socialAuthorDisplayName: `Mock Account ${handle}`,
        socialAuthorProfileUrl: `https://${source.domain}/${handle}`,
        // Deterministic but varying, so the UI has something real to
        // render ("Unknown" would be true for every row otherwise) —
        // never randomized (this must stay reproducible across fetches
        // of the same bucket for dedupe's sake).
        socialAuthorFollowers: 100 * ((bucket % 50) + 1),
        socialAuthorVerified: bucket % 7 === 0,
      },
    ];
  }

  async healthCheck(_source: Source): Promise<SourceHealth> {
    return { status: "healthy" };
  }
}
