#!/usr/bin/env node
/**
 * Refreshes the copies of the brand-kit logo that the code reads:
 *  - apps/web/public/brand/*.png (web-sized, served by the app)
 *  - packages/reports/src/brand.generated.ts (base64, embedded in report, archive and export files)
 * Usage: pnpm exec tsx scripts/build-brand-assets.ts
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const logo = (name: string) => path.join(root, "brand-kit/logo", name);
const colors = JSON.parse(readFileSync(path.join(root, "brand-kit/colors.json"), "utf8")) as Record<string, string | string[]>;

const web = path.join(root, "apps/web/public/brand");
mkdirSync(web, { recursive: true });
const sizes: [string, number][] = [["mediaory-logo.png", 640], ["mediaory-logo-light.png", 640], ["mediaory-mark.png", 256]];
for (const [name, width] of sizes) {
  await sharp(logo(name)).resize({ width }).png({ compressionLevel: 9 }).toFile(path.join(web, name));
}

const embedded = async (name: string, width: number) => {
  const png = await sharp(logo(name)).resize({ width }).png({ compressionLevel: 9, palette: true, quality: 90 }).toBuffer();
  return `data:image/png;base64,${png.toString("base64")}`;
};
const out = `// GENERATED by scripts/build-brand-assets.ts from brand-kit/ — do not edit by hand.
export const BRAND_LOGO_DATA_URI = ${JSON.stringify(await embedded("mediaory-logo.png", 420))};
export const BRAND_LOGO_LIGHT_DATA_URI = ${JSON.stringify(await embedded("mediaory-logo-light.png", 420))};
export const BRAND_MARK_DATA_URI = ${JSON.stringify(await embedded("mediaory-mark.png", 128))};
export const BRAND_COLORS = ${JSON.stringify(colors, null, 2)} as const;
`;
writeFileSync(path.join(root, "packages/reports/src/brand.generated.ts"), out);
console.log("Brand assets refreshed.");
