#!/usr/bin/env node
/**
 * Regenerates packages/core/src/source-catalog.generated.ts from a Markdown
 * list of Turkish RSS feeds (tables of `| Site name | RSS URL |` under `# Category`
 * headings), such as the community list at https://github.com/bakinazik/rss.
 *
 * Only the facts we need are copied — outlet name, feed URL and category — never
 * the list's prose. Nothing here decides whether a feed may be used: at runtime
 * the catalog drops licence-required agencies (restricted-publishers.ts), and
 * /admin/sources fetch-tests every feed before it is stored.
 *
 * Usage: pnpm exec tsx scripts/import-rss-catalog.ts <README.md path or https URL>
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const GROUPS: Record<string, string> = {
  "Gündem": "general",
  "Spor": "sports",
  "Ekonomi ve Finans": "economy",
  "İş Dünyası": "business",
  "Teknoloji": "technology",
  "Bilim": "science",
  "Kültür ve Sanat": "culture",
  "Eğlence": "entertainment",
  "Yaşam": "lifestyle",
  "Savunma ve Sanayi": "defense",
};

const source = process.argv[2];
if (!source) {
  console.error("Usage: pnpm exec tsx scripts/import-rss-catalog.ts <README.md path or https URL>");
  process.exit(1);
}
const markdown = /^https?:/.test(source) ? await (await fetch(source)).text() : readFileSync(source, "utf8");

const slug = (value: string) =>
  value
    .toLocaleLowerCase("tr")
    .replace(/ı/g, "i").replace(/ğ/g, "g").replace(/ü/g, "u").replace(/ş/g, "s").replace(/ö/g, "o").replace(/ç/g, "c")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

let category = null;
const seenUrls = new Set();
const seenKeys = new Set();
const entries: { key: string; name: string; url: string; group: string }[] = [];
for (const line of markdown.split(/\r?\n/)) {
  if (line.startsWith("# ")) {
    category = line.slice(2).trim();
    continue;
  }
  const match = line.match(/^\|\s*(.+?)\s*\|\s*(\S+)\s*\|\s*$/);
  const group = category ? GROUPS[category] : undefined;
  if (!match || !group || !/^https:\/\//.test(match[2])) continue;
  const [, name, rawUrl] = match;
  let url: string;
  try {
    url = new URL(rawUrl).toString();
  } catch {
    continue;
  }
  if (seenUrls.has(url)) continue;
  seenUrls.add(url);
  let key = `rss-${slug(name)}`;
  for (let i = 2; seenKeys.has(key); i++) key = `rss-${slug(name)}-${i}`;
  seenKeys.add(key);
  entries.push({ key, name, url, group });
}

const q = (s: string) => JSON.stringify(s);
const body = entries
  .map((e) => `  { key: ${q(e.key)}, name: ${q(e.name)}, url: ${q(e.url)}, type: "news", language: "tr", country: "TR", group: ${q(e.group)} },`)
  .join("\n");
const out = `// GENERATED by scripts/import-rss-catalog.ts — do not edit by hand.
// Outlet names and feed URLs only, from a community list of Turkish RSS feeds
// (https://github.com/bakinazik/rss). Candidates, not permissions: see source-catalog.ts.
import type { CatalogSource } from "./source-catalog";

export const GENERATED_CATALOG: readonly CatalogSource[] = [
${body}
];
`;
const target = path.join(path.dirname(fileURLToPath(import.meta.url)), "../packages/core/src/source-catalog.generated.ts");
writeFileSync(target, out);
console.log(`Wrote ${entries.length} feeds to ${target}`);
