#!/usr/bin/env node
/**
 * Regenerates packages/core/src/startup-catalog.generated.ts from the operator's
 * startup / project-funding directories (scripts/data/Turkiye_Startup_Proje.md and
 * scripts/data/Proje_Yazanlar_ve_Kuluckalar.md, checked 6 Oct 2026).
 *
 * Two kinds of rows come out:
 *  - FEEDS: the directory lists an RSS/Atom address. Copied as a candidate; the
 *    worker fetch-tests it before it is stored.
 *  - PAGES: the directory found no RSS ("RSS adresi belirlenmedi") and lists the
 *    organisation's web page. The worker's feed discovery looks for a feed there
 *    (page <link rel="alternate"> or the usual paths, robots.txt permitting) and
 *    stores the source only if one reads. A page with no feed is simply not added.
 *
 * Only facts are copied (name, address, country, the directory's own category).
 * Licence-required agencies are dropped, a feed counts once however it is written,
 * and a page on a host that already has a feed is left out.
 *
 * Usage: pnpm exec tsx scripts/import-startup-pack.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { feedIdentity } from "../packages/core/src/source-catalog";
import { hostOfUrl, isLicenseRequiredHost } from "../packages/core/src/restricted-publishers";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const files = ["Turkiye_Startup_Proje.md", "Proje_Yazanlar_ve_Kuluckalar.md"].map((f) => path.join(root, "scripts/data", f));
/** Turkish country name → ISO code (null when the name is a region or has no code). */
const countryNames: Record<string, string | null> = JSON.parse(
  readFileSync(path.join(root, "scripts/data/world-country-names-tr.json"), "utf8"),
);
const codeOf = new Map<string, string>();
for (const [name, code] of Object.entries(countryNames)) if (code) codeOf.set(name, code);
// Names the shared country list leaves without a code.
codeOf.set("BAE", "AE");
const ENGLISH = new Set(["US", "GB", "CA", "AU", "NZ", "IE", "IN", "SG", "HK", "ZA", "KE", "NG"]);

type Row = { name: string; url: string; country: string; language: string; type: string; verified: boolean; feed: boolean };
const rows: Row[] = [];

for (const file of files) {
  let region = "";
  let kind = "";
  for (const line of readFileSync(file, "utf8").split(/\r?\n/)) {
    if (line.startsWith("## ")) {
      [region = "", kind = ""] = line.slice(3).split("→").map((s) => s.trim());
      continue;
    }
    if (!line.startsWith("| ") || line.startsWith("| ---") || line.startsWith("| Kurum")) continue;
    const cells = line.replace(/^\||\|\s*$/g, "").split(" | ").map((c) => c.trim());
    if (cells.length < 4) continue;
    const link = /\[([^\]]*)\]\(([^)]+)\)/.exec(cells[2]!);
    if (!link) continue;
    const feed = link[1]!.startsWith("RSS");
    let url: string;
    try {
      const u = new URL(link[2]!);
      if (u.protocol === "http:") u.protocol = "https:";
      if (u.protocol !== "https:") continue;
      url = u.toString();
    } catch {
      continue;
    }
    const country = region.includes("/") ? "" : (codeOf.get(region) ?? "");
    rows.push({
      name: cells[0]!.replace(/\s+/g, " "),
      url,
      country,
      language: country === "TR" ? "tr" : ENGLISH.has(country) ? "en" : "",
      type: kind === "Startup medyası" ? "news" : kind.includes("blog") ? "blog" : "website",
      verified: feed && cells[3]!.startsWith("XML ve içerik doğrulandı"),
      feed,
    });
  }
}

const seen = new Set<string>();
const feedHosts = new Set<string>();
const feeds: Row[] = [];
for (const row of rows.filter((r) => r.feed)) {
  const host = hostOfUrl(row.url);
  if (!host || isLicenseRequiredHost(host)) continue;
  const id = feedIdentity(row.url);
  if (seen.has(id)) continue;
  seen.add(id);
  feedHosts.add(host);
  feeds.push(row);
}
const pageSeen = new Set<string>();
const pages: Row[] = [];
for (const row of rows.filter((r) => !r.feed)) {
  const host = hostOfUrl(row.url);
  if (!host || isLicenseRequiredHost(host) || feedHosts.has(host)) continue;
  const id = feedIdentity(row.url);
  if (pageSeen.has(id)) continue;
  pageSeen.add(id);
  pages.push(row);
}

const q = (s: string) => JSON.stringify(s);
const line = (r: Row) => `[${q(r.name)},${q(r.url)},${q(r.country)},${q(r.language)},${q(r.type)},${r.verified ? 1 : 0}]`;
const out = `// GENERATED by scripts/import-startup-pack.ts from the operator's startup / project-funding directories (checked 2026-10-06).
// Do not edit by hand — re-run the script. Candidates, not guarantees: every feed is fetch-tested before it is stored.
// Row: [name, address, ISO country ("" = global / several), language ("" = unknown), Source.type, directory's own XML check passed (1/0)]
export type StartupRow = readonly [string, string, string, string, string, 0 | 1];

/** The directory lists an RSS/Atom address. */
export const STARTUP_FEED_ROWS: ReadonlyArray<StartupRow> = [
${feeds.map((r) => `  ${line(r)},`).join("\n")}
];

/** The directory found no RSS; this is the organisation's web page — a feed is looked for there. */
export const STARTUP_PAGE_ROWS: ReadonlyArray<StartupRow> = [
${pages.map((r) => `  ${line(r)},`).join("\n")}
];
`;
writeFileSync(path.join(root, "packages/core/src/startup-catalog.generated.ts"), out);
console.log(`Wrote ${feeds.length} feeds and ${pages.length} pages.`);
